on: 
  push: 
    branches: 
    - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
      - name: Check out code
        uses: actions/checkout@v1
      - name: Test
        run: CGO_ENABLED=0 go test ./... -v
      - name: Build
        run: make build
      - name: Upload
        env:
          GORP_TOKEN: {{secrets.GORP_TOKEN}}
          GORP_URL: {{secrets.GORP_URL}}
        run: env && curl -i -H "Authorization: $GORP_TOKEN" -F file=@$(make print-bin) $GORP_URL 