on: 
  push: 
    branches: 
    - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.12

      - name: Check out code
        uses: actions/checkout@v1
      - name: Show env
        run: env
      - name: Build
        run: go build -o app main.go